language: python
python:
  - "2.7"
install:
  #- pip install pep8 --use-mirrors
  #- pip install pyflakes --use-mirrors
  - pip install robotframework
  - pip install robotframework-selenium2library
  - pip install selenium
  - pip install decorator
  - pip install docutils
  #- pip install gevent
  #- pip install pyzmq
  #- pip install zerorpc
  #- "if [[ ${BROWSER} == 'ie' ]]; then pip install ie_only_pkg; fi"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
script:
  - "pybot --variable USERNAME:$S_USERNAME --variable ACCESS_KEY:$S_ACCESS_KEY --outputdir /home/travis/build/Rafikhan29/SauceLabs_Gmail/results/ /home/travis/build/Rafikhan29/SauceLabs_Gmail/tests/valid_login.txt"
  #- python client.py
  - cd /home/travis/build/Rafikhan29/SauceLabs_Gmail/
  - zip -r results.zip results
  - cd /home/travis/build/Rafikhan29/SauceLabs_Gmail/
  - ls
  - cd /home/travis/build/Rafikhan29/SauceLabs_Gmail/results/
  - ls
  - cd /home/travis/build/Rafikhan29/SauceLabs_Gmail/
  - python sendEmailQA.py /home/travis/build/Rafikhan29/SauceLabs_Gmail/
  
#after_success: 
    
        #zip -r results.zip /home/travis/build/Rafikhan29/SauceLabs_Gmail/results/
        #- cat /home/travis/build/Rafikhan29/SauceLabs_Gmail/results/log.html
        #- cd /home/travis/build/Rafikhan29/SauceLabs_Gmail/results/
        #- ls
        
env:
  global:
    - S_USERNAME=Rafikhan29
    - S_ACCESS_KEY=47ab59b8-9b87-4433-8fa1-b02111cabbba
