language: python
python:
  - "2.7"
install:
  #- pip install pep8 --use-mirrors
  #- pip install pyflakes --use-mirrors
  - pip install robotframework
  - pip install robotframework-selenium2library
  - pip install selenium
  - pip install decorator
  - pip install docutils
  # - pip install zerorpc
  #- "if [[ ${BROWSER} == 'ie' ]]; then pip install ie_only_pkg; fi"

env:
  global:
    - S_USERNAME=Rafikhan29
    - S_ACCESS_KEY=47ab59b8-9b87-4433-8fa1-b02111cabbba
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
script:

  - "pybot --variable SAUCE_USERNAME:$SAUCE_USERNAME --variable SAUCE_ACCESS_KEY:$SAUCE_ACCESS_KEY --outputdir MyBuild /home/travis/build/Rafikhan29/SauceLabs_Gmail/tests/valid_login.txt"